### ISSUE TITLE
Session not persistent when using database as session driver

### ISSUE THREAD

**Issue by nielsvandoorn** [auth0-samples/auth0-laravel-php-web-app#10]
Hi there,

Because of my production environment I need to use the database as a session driver. You do this by setting the SESSION_DRIVER in the .env file to database. Unfortunately whenever I try to login the Authentication with Auth0 wil succeed, but the Authentication inside of Laravel is not working. l keep getting redirected to the login page. Works fine when using "file" as SESSION_DRIVER.

**Comment by mchainanicimpress** [comment]
@nielsvandoorn did you find a solution for this?

**Comment by nielsvandoorn** [comment]
@mchainanicimpress Sorry for the late response. We fixed this by using redis as the session driver

**Comment by mchainanicimpress** [comment]
@nielsvandoorn I did something similar by using cookie

**Comment by vomitHatSteve** [comment]
So this has been plaguing me for a few days.

Why does the database session driver not load a just-saved session correctly?
