### ISSUE TITLE
How to implement universal logout?

### ISSUE THREAD

**Issue by prasanthka01** [auth0-samples/auth0-laravel-php-web-app#105]
We have clients that use Spotfire on their machines (separate credentials from Auth0) and what happens when they login to Auth0 is that they get signed in to Spotfire via Auth0 credentials. But when they Sign Out from Auth0, they’re not signed out from Spotfire license/credentials – is there a way to ensure they get signed out from Spotfire/Auth0?

"auth0/login": "^5.0"
Laravel Framework
public function logout()
{
Auth::logout();

    $logoutUrl = sprintf(
        'https://%s/v2/logout?federated&client_id=%s&returnTo=%s',
        config('laravel-auth0.domain'),
        config('laravel-auth0.client_id'),
        config('app.url')
    );

    return Redirect::intended($logoutUrl);

    return redirect()->route('home');
}

**Comment by evansims** [comment]
Hi @prasanthka01 👋 Not sure what Spotfire is, but how you'd approach clearing out a session for another library depends somewhat on the approach they're using to implement it, how they're handling their session data, and so forth. You can review [the logout endpoint guide here](https://auth0.com/docs/login/logout). It's possible the Auth0 session and IdP layers are being cleared successfully, but Spotfire has local cookies or a PHP session in play that are keeping you signed in there. I'm not sure that I can offer much guidance there outside of looking into how Spitfire manages their sessions and writing custom logout code to handle both sessions.

**Comment by evansims** [comment]
Closing this for now, as it's been some time without a response. Let me know if you'd like to continue discussing this and we can re-open it.
