### ISSUE TITLE
Auth0 in Laravel not working

### ISSUE THREAD

**Issue by LozziStyle** [auth0-samples/auth0-laravel-php-web-app#146]
Hello everyone,

I followed this guide: https://auth0.com/docs/quickstart/webapp/laravel/01-login

But Auth::user() returns null all the time. Why is that so?

**Comment by evansims** [comment]
Hi @LozziStyle 👋 Hard to say, we'd need further details to diagnose. Does the application in this repository work for you?

**Comment by LozziStyle** [comment]
Hi Evan,

my PO and I tried to get the laravel example into a working state. Unfortunately it didnt work. It always told us that the guard auth0 driver is undefined: "**auth driver [auth0] for guard [auth0] is not defined.**"

**We tried following:**

- Installed the sdk
- Deployed the example project fork with the right .env and vapor.yml (we're deploying with laravel vapor)
- (Installed laravel/vapor-core for deployment)
- composer install (and update)

But we still had no success in running this example project.

We also noticed that the sdk used in this example is not the one you get when you run `php artisan vendor:publish --tag auth0-config`, it seems like the config in this example is a bit outdated, which is why we couldnt solve our current problem by copying your example config into our project.

Everything is working fine in our project, except the authorized state. After a successful login you're always redirected into the start page, where you are called a guest (whilst you shouldnt be). --> Our guess is that this has to do something about the issue I talked in my first message about. (Auth::user() returning null).

Do you have any suggestions? Or even better: are you free sometime to talk about our issue in a lets say discord call for example?

**Comment by LozziStyle** [comment]
We managed to solve this issue by updating auth0-sdk with `composer update`... 😅

For anyone having the same issue. This issue is resolved.
