### ISSUE TITLE
WebApp Laravel Quickstart: Incorrect command use in readme.md file

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-laravel-php-web-app#19]
Incorrect command use in readme.md file:
The right command is:
composer install instead it's using: php composer.phar install

![image](https://user-images.githubusercontent.com/26749061/33435293-2906fd2e-d5b8-11e7-8af7-8b9ca54d0d60.png)

**Comment by joshcanhelp** [comment]
The command will be different depending on how you have Composer installed. Addressing this in #24.
