### ISSUE TITLE
Feedback from customer

### ISSUE THREAD

**Issue by lobo** [auth0-samples/auth0-laravel-php-web-app#3]
`Auth0::getUser()` doesn't work and `Auth0::jwtUser()` doesn't have a name property.

**Comment by unicodeveloper** [comment]
It works. The developer might have omitted a step in setting it up. After installing the auth0/login package from composer publishing the config file, he should ensure he actually carried out these two actions below:

1. Add `Auth0\Login\LoginServiceProvider` to the providers array  in `config/app.php`
2. Add ` 'Auth0' => 'Auth0\Login\Facade\Auth0'` to the aliases array in `config/app.php`
