### ISSUE TITLE
invalid_request: The redirect_uri parameter is not valid: 

### ISSUE THREAD

**Issue by avrahamm** [auth0-samples/auth0-laravel-php-web-app#32]
![auth0error](https://user-images.githubusercontent.com/22640786/47357845-9cfa6f80-d6d0-11e8-804f-1077827337f5.PNG)
Hi, I tried to integrate Auth0 into my laravel app according to Auth0 Laravel Quickstart,
made all the steps,

It redirects me to 
https://wallter.eu.auth0.com/authorize?response_mode=query&scope=openid%20email%20email_verified&response_type=code&redirect_uri=local.accounts.wallter%2Fauth0%2Fcallback&client_id=UGvJrnvKhNZls8VPSUDTYEDxMwMCNcNp&state=5bcdeeb7627e75.25065676

wallter
Oops!, something went wrong
nvalid_request: The redirect_uri parameter is not valid: "local.accounts.wallter/auth0/callback" If url looks fine, check that you are not including non printable chars

I tried to google yet found nothing.
Any Idea? Can you please help? 

Thanks, 
Sincerely,
Avraham

**Comment by joshcanhelp** [comment]
Hi @avrahamm! You need a complete URI in that `redirect_uri` parameter. So change `redirect_uri=local.accounts.wallter%2Fauth0%2Fcallback` to `redirect_uri=http://local.accounts.wallter%2Fauth0%2Fcallback`

**Comment by avrahamm** [comment]
Thanks a lot! it helped.
