### ISSUE TITLE
Dependency update results in Laravel error "Cannot handle token prior to [timestamp]"

### ISSUE THREAD

**Issue by glaesser** [auth0-samples/auth0-laravel-php-web-app#33]
Both projects here (00-Starter-Seed and 01-Login) work flawlessly once downloaded and installed. However, upon running "composer update" to update dependencies, both projects throw the same error upon trying to login:

> Auth0 \ SDK \ Exception \ CoreException
> Cannot handle token prior to 2019-01-09T09:25:15+0000

Potentially stems the following dependency updates:

> Updating auth0/auth0-php (5.1.0 => 5.3.2)
> Updating auth0/login (5.0.2 => 5.1.0)

Googling around hasn't produced any fixes that work in this case. Would love to get this up and running again!

**Comment by glaesser** [comment]
Update: after more testing, it appears this issue is due to my local machine's system time being off by ~20 seconds. (MacOS 10.14.2 w/ automatic time sync from apple enabled). 

As this issue is more likely to surface on local dev machines vs. a production server running NTP to keep time in sync, is there a way to manually set "leeway" in seconds (for testing purposes only)?

**Comment by rdowinton** [comment]
The Auth0 PHP SDK doesn't have a leeway option (as far as I can tell). 

However, it uses the [PHP-JWT library](https://github.com/firebase/php-jwt) which supports a `leeway` option (static variable, see [here](https://github.com/firebase/php-jwt/blob/bac0422822b92fe7a0ed1fc7b1b633d9efa37bae/src/JWT.php#L30)). 

So for testing you could always modify [JWTVerifier](https://github.com/auth0/auth0-PHP/blob/master/src/JWTVerifier.php#L240) to set the `leeway`  before it decodes the token, e.g:

```
    protected function decodeToken($jwt, $secret)
    {
        return JWT::decode($jwt, $secret, $this->supported_algs);
    }
```
->
```
    protected function decodeToken($jwt, $secret)
    {
        JWT::$leeway = 60;
        return JWT::decode($jwt, $secret, $this->supported_algs);
    }
```

**Comment by glaesser** [comment]
Thank you for pointing that out - very useful. I think we can close this issue now.
