### ISSUE TITLE
Users not inserted to users table

### ISSUE THREAD

**Issue by debeniter86** [auth0-samples/auth0-laravel-php-web-app#6]
Hi,

I have tried this.Users are added to Auth0 users list but not inserted to my database. How can I fixed this?

**Comment by joshcanhelp** [comment]
Very belated reply but that is not handled by this seed project. We do cover it in the [QuickStart](https://auth0.com/docs/quickstart/webapp/laravel#extend-the-auth0userrepository-class), though.
