### ISSUE TITLE
Laravel SDK deletes port numbers by itself

### ISSUE THREAD

**Issue by nnahito** [auth0-samples/auth0-laravel-php-web-app#81]
I am creating a new project in Laravel8.
I installed the Auth0 SDK into Laravel with the following command.

```
$ composer require auth0/login
```

Then I set the "Allowed Callback URLs" of Auth0 as follows.

```
http://localhost:8080/auth0/callback
```

I wrote the code for the login part of Laravel as follows.

```
    public function login()
    {
        $authorize_params = [
            'scope' => 'openid email email_verified',
            // Use the key below to get an Access Token for your API.
            // 'audience' => config('laravel-auth0.api_identifier'),
        ];

        return app()->make('auth0')->login(null, null, $authorize_params);
    }
```

When this code is executed, the parameter of "redirect_url" will be "http://localhost/auth0/callback".
The port number will be erased by itself.

Why is this?

**Comment by evansims** [comment]
Hi @nnahito 👋  Sorry to hear you're having trouble on this! Can I ask what APP_URL you have specified in your .env file? The redirect_url param [should be based on that value.](https://github.com/auth0-samples/auth0-laravel-php-web-app/blob/master/01-Login/config/laravel-auth0.php#L40)

**Comment by nnahito** [comment]
Thank you for your reply.
The "APP_URL" set in Laravel's .env is "http://localhost".

**Comment by evansims** [comment]
You just need to specify the port, either in your APP_URL or by manually setting the redirect_uri in your $authorized_params array.
