### ISSUE TITLE
Error on logout in Laravel SDK.

### ISSUE THREAD

**Issue by nnahito** [auth0-samples/auth0-laravel-php-web-app#82]
I set up the SDK for Laravel using your help pages.
When the following code is executed, the I get the following error.

```
    public function logout()
    {
        Auth::logout();

        $logoutUrl = sprintf(
            'https://%s/v2/logout?client_id=%s&returnTo=%s',
            config('laravel-auth0.domain'),
            config('laravel-auth0.client_id'),
            config('app.url')
        );

        return Redirect::intended($logoutUrl);
    }
```

```
There could be a misconfiguration in the system or a service outage. We track these errors automatically, but if the problem persists feel free to contact us.
Please try again. 
```

Please tell me how to fix this.

**Comment by evansims** [comment]
Hi @nnahito 👋 That error is a bit ambiguous, but I'm guessing there is a mismatch between your Laravel configuration and what you have set up with your Auth0 dashboard. Is the returnTo URL identical to what you have set up in your Auth0 Application's "Allowed Logout URLs", in the Auth0 Dashboard?

Can you try dumping those config values and ensuring they're all matching up with your Auth0 application settings? Then we can go from there 👍

**Comment by nnahito** [comment]
Thank you for your reply.
The "Allowed Logout URLs" setting is consistent.
Both Auth0 and the access point are set to "http://localhost/logout".

**Comment by evansims** [comment]
Can you echo your $logoutUrl var and share it with me? Maybe something obvious isn't showing up.

Beyond the obvious, there doesn't appear to be anything really relating to the Laravel SDK or Quickstart on this, you may need to reference the API documentation for this endpoint at https://auth0.com/docs/api/authentication?http#logout or ask for guidance in the Auth0 Community https://community.auth0.com/

**Comment by nnahito** [comment]
here is  `$logoutUrl`.
https://develop-nthk.jp.auth0.com/v2/logout?client_id=NRtj2cxZH6WfonMRmMn4lZJJBTAAxdwc&returnTo=http://localhost

**Comment by evansims** [comment]
Your returnTo is pointing to http://localhost, rather than http://localhost/logout

**Comment by nnahito** [comment]
I was wrong in my understanding.
In the "Allowed Logout URLs" field,I don't write the URL for the logout process, but the URL for the redirect after logout.
It worked correctly.
Thank you very much for your help.
